apiVersion: v1
kind: Secret
metadata:
  name: ticket-service-secrets
  namespace: ticketing
type: Opaque
stringData:
  SECRET_KEY: "super_secret_production_key_change_me"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "secureproductionpassword"
